{
 "title": "Meta - MTA/USDT",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "pair", "label": "Spot Pair", "query": "${VAR_PAIR}" },
   { "name": "bot", "label": "Bot", "query": "${VAR_BOT}" },
   { "name": "tokenSymbol", "query": "${VAR_TOKENSYMBOL}" }
  ]
 },
 "panels": [
  {
   "title": "Est. Bot Revenue (usd)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "balances",
     "query": "SELECT last(\"value\") - first(\"value\") FROM \"balances\" WHERE (\"address\"=~ /^$bot$/)  AND (\"type\" = 'usd') AND (\"tokenSymbol\" = 'total') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "address",
       "operator": "=",
       "value": "0xdbd09c24a86f5475871f95b0fbc7fa5d1822f9ab"
      }
     ]
    }
   ]
  },
  {
   "title": "New Spot Users - $pair",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "balances",
     "query": "SELECT last(\"value\") - first(\"value\") FROM \"total_users\" WHERE (\"pair\" =~ /^$pair$/ AND \"env\" = 'mainnet' AND \"duration\" = 'all') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "address",
       "operator": "=",
       "value": "0xdbd09c24a86f5475871f95b0fbc7fa5d1822f9ab"
      }
     ]
    }
   ]
  },
  {
   "title": "Spot Trades - $pair",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "balances",
     "query": "SELECT last(\"value\") - first(\"value\") FROM \"total_trades\" WHERE (\"env\" = 'mainnet' AND \"pair\" =~ /^$pair$/ AND \"duration\" = 'spotall') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "address",
       "operator": "=",
       "value": "0xdbd09c24a86f5475871f95b0fbc7fa5d1822f9ab"
      }
     ]
    }
   ]
  },
  {
   "title": "Bot Balances (usd)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"value\") FROM \"balances\" WHERE (\"address\"=~ /^$bot$/ AND \"tokenSymbol\" = 'total' AND \"type\" = 'usd') AND $timeFilter GROUP BY time(30m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Spot Users - $pair",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "all",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_users",
     "query": "SELECT max(\"value\") FROM \"total_users\" WHERE (\"pair\" =~ /^$pair$/ AND \"env\" = 'mainnet' AND \"duration\" = 'all') AND $timeFilter GROUP BY time(30m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "pair", "operator": "=~", "value": "/^$pair$/" },
      { "condition": "AND", "key": "env", "operator": "=", "value": "mainnet" },
      { "condition": "AND", "key": "duration", "operator": "=", "value": "all" }
     ]
    },
    {
     "alias": "24h",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_users",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "pair", "operator": "=~", "value": "/^$pair$/" },
      { "condition": "AND", "key": "env", "operator": "=", "value": "mainnet" },
      { "condition": "AND", "key": "duration", "operator": "=", "value": "24h" }
     ]
    },
    {
     "alias": "7d",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_users",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "pair", "operator": "=~", "value": "/^$pair$/" },
      { "condition": "AND", "key": "env", "operator": "=", "value": "mainnet" },
      { "condition": "AND", "key": "duration", "operator": "=", "value": "7d" }
     ]
    },
    {
     "alias": "30d",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_users",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "pair", "operator": "=~", "value": "/^$pair$/" },
      { "condition": "AND", "key": "env", "operator": "=", "value": "mainnet" },
      { "condition": "AND", "key": "duration", "operator": "=", "value": "30d" }
     ]
    }
   ]
  },
  {
   "title": "Spot Trades - $pair",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "all",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_trades",
     "query": "SELECT last(\"value\") FROM \"total_trades\" WHERE \"pair\" = 'all' AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=", "value": "mainnet" },
      { "condition": "AND", "key": "pair", "operator": "=~", "value": "/^$pair$/" },
      { "condition": "AND", "key": "duration", "operator": "=", "value": "spotall" }
     ]
    },
    {
     "alias": "24h",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_trades",
     "query": "SELECT last(\"value\") FROM \"total_trades\" WHERE \"pair\" = 'all' AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=", "value": "mainnet" },
      { "condition": "AND", "key": "pair", "operator": "=~", "value": "/^$pair$/" },
      { "condition": "AND", "key": "duration", "operator": "=", "value": "spot24h" }
     ]
    },
    {
     "alias": "30d",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_trades",
     "query": "SELECT last(\"value\") FROM \"total_trades\" WHERE \"pair\" = 'all' AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=", "value": "mainnet" },
      { "condition": "AND", "key": "pair", "operator": "=~", "value": "/^$pair$/" },
      { "condition": "AND", "key": "duration", "operator": "=", "value": "spot30d" }
     ]
    },
    {
     "alias": "7d",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_trades",
     "query": "SELECT last(\"value\") FROM \"total_trades\" WHERE \"pair\" = 'all' AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=", "value": "mainnet" },
      { "condition": "AND", "key": "pair", "operator": "=~", "value": "/^$pair$/" },
      { "condition": "AND", "key": "duration", "operator": "=", "value": "spot7d" }
     ]
    }
   ]
  },
  {
   "title": "TRC21 $tokenSymbol Total Supply",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "trc21tokens",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$tokenSymbol$/" }
     ]
    }
   ]
  },
  {
   "title": "Desposit/Withdraw TX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "depositTx",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "txdeposit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$tokenSymbol$/" }
     ]
    },
    {
     "alias": "withdrawTx",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "txwithdraw",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$tokenSymbol$/" }
     ]
    }
   ]
  }
 ]
}